name: templets
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  provider: ^4.0.1
  shared_preferences: ^0.5.3+1
  logger: ^0.9.4
  flutter_secure_storage: ^3.3.3
  location: ^2.5.0
  math_expressions: ^2.0.0
  flutter_colorpicker: ^0.3.4
  dotted_border: ^1.0.5
  keyboard_avoider: ^0.1.2
  configurable_expansion_tile: ^1.0.0
  signature: ^3.0.0
  video_player: ^0.10.12+5
  chewie: ^0.9.10
  webview_flutter: ^0.3.22+1
  flutter_html: ^1.0.0
  email_validator: ^1.0.0
  image_picker: ^0.6.7+1
  percent_indicator: ^2.1.1
  advance_pdf_viewer: any
  barcode_scan: ^1.0.0
  url_launcher: ^5.0.3
  google_maps_flutter: ^0.5.13
  popup_menu: ^1.0.5
  auto_direction: ^0.0.4+1
  open_file: any
  dio: 3.0.9
  arabic_numbers: ^0.0.1
  google_api_headers: ^0.1.0
  flutter_google_places: ^0.2.5
  app_settings: ^4.0.3
  file_picker: any
  permission_handler: ^5.0.1
  intl: ^0.16.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - logo.png
    - no-photo.png
    - file.png
    - SideMenuBackground.png
    - application.png
    - listss.png
    - bell.png
    - dashboard.png
    - settings.png
    - vodafone.png
    - setting-login.png
    - background.png
    - stage-logo.png
    - ffff.png
    - ntg_logo.png
    - Splash_Copy.png
    - assets/bg_login.png
    - assets/bg_menu.png
    - assets/bg_splash.png
    - assets/bttn_add.png
    - assets/bttn_back.png
    - assets/bttn_calendarday.png
    - assets/bttn_edit.png
    - assets/bttn_menuwhite.png
    - assets/bttn_search.png
    - assets/ic_arrowcell.png
    - assets/ic_attached.png
    - assets/ic_calnedartxt.png
    - assets/ic_changepassword.png
    - assets/ic_clocktxtfield.png
    - assets/ic_close.png
    - assets/ic_companysettings.png
    - assets/ic_dropdown.png
    - assets/ic_duplicatefield.png
    - assets/img_faqbbg.png

    - assets/ic_editprofile.png
    - assets/ic_imgupload.png
    - assets/ic_info.png
    - assets/ic_language.png
    - assets/ic_lockfield.png
    - assets/ic_mytaskstodo.png
    - assets/ic_mytaskstodoarrow.png
    - assets/ic_newspaper.png
    - assets/ic_notificiation.png
    - assets/ic_pdf.png
    - assets/ic_pushsetting.png
    - assets/ic_showpassword.png
    - assets/ic_txtfieldcheck.png
    - assets/ic_warningpopup.png
    - assets/ic_zip.png
    - assets/illustrate_companysettings.png
    - assets/illustrate_language.png
    - assets/illustrate_password.png
    - assets/illustrate_push.png
    - assets/img_poweredbyntg.png
    - assets/img_settingbg.png
    - assets/stage_logo.png
    - assets/NTGApps_logo.png
    - assets/ic_delete.png
    - assets/ic_menu.png
    - assets/ic_contactus.png
    - assets/ic_faq.png
    - assets/ic_qrcode.png
    - assets/ic_qrcodeedit.png
    - assets/ic_todocalendar.png
    - assets/ic_closex.png
    - assets/ic_todochecked.png
    - assets/ic_todounchecked.png
    - assets/img_profileplaceholder.png
    - assets/bttn_workingdaysnhours.png
    - assets/ic_notificationred.png
    - assets/ic_todoalcaughtup.png
    - assets/ic_addtask.png
    - assets/ic_notifications_active.png
    - assets/ic_notifications_inactive.png
    - assets/file_compressed.png
    - assets/file_doc.png
    - assets/file_generic.png
    - assets/file_img.png
    - assets/file_pdf.png
    - assets/file_sound.png
    - assets/file_txt.png
    - assets/file_video.png
    - assets/ic_note_active.png
    - assets/ic_note_inactive.png
    - assets/add_girdblue.png
    - assets/add_gridnew.png
    - assets/download_bttn.png
    - assets/ic_attacheddownload.png
    - assets/ic_editgrid.png
    - assets/ic_filter.png
    - assets/ic_sort.png
    - assets/ic_incomplete_task.png
    - assets/ic_completed_task.png
    - assets/search_2.png
    - assets/sort.png
    - assets/time.png
    - assets/search2.png
    - assets/filter.png
    - assets/edit2.png
    - assets/delete2.png
    - assets/notification2.png
    - assets/notification_seen2.png
    - assets/apps_temp2.png
    - assets/dashboard_temp2.png
    - assets/shortcuts_temp2.png
    - assets/sticky-notes_temp2.png
    - assets/tasks_temp2.png
    - assets/add2.png
    - assets/temp2_add_new.png
    - assets/temp2_edit.png
    - assets/temp2_delete.png
    - assets/temp2_add_blue.png
    - assets/temp2_date.png
    - assets/temp2_time.png
    - assets/temp2_date_time.png
    - assets/uploadAttach2.png
    - assets/note2.png
    - assets/download2.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
